
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 139
#define YY_END_OF_BUFFER 140
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[370] =
    {   0,
        1,    1,  140,  139,    7,    1,   74,  139,   67,   93,
      139,   55,   56,   65,   63,   59,   64,  139,   66,   98,
       57,   58,   70,   68,   71,   69,   50,   50,   53,   72,
       54,  139,  139,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       51,   94,   52,   73,  138,    1,   90,    6,   60,   61,
       99,    0,    0,   91,    0,    0,    5,  137,  137,   75,
       62,   96,    0,  103,  136,    0,   98,    0,   95,   80,
       83,   78,   76,   77,   79,   88,   89,   87,   84,   85,
        0,   50,    0,   97,   50,   50,   50,   16,   50,   50,

       22,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   44,   50,   50,   50,
       50,    0,   92,    0,  100,  101,  102,    2,    0,    0,
        2,    0,  137,  137,  104,    0,    0,    0,  108,   86,
       82,   81,    0,  135,    0,  134,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   28,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   41,   50,   50,   50,   50,   50,
       50,   50,  133,    0,  113,    0,    0,    0,    3,    0,
        3,    4,  137,  105,  106,  107,  109,    0,    0,   50,

       50,   10,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   31,
       50,   50,   50,   35,   36,   37,   50,   50,   40,   42,
       50,   45,   50,   50,   50,   50,  114,    0,    0,    0,
      118,    0,  123,    0,  128,  110,  111,  112,    8,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   30,   50,   33,   50,
       50,   50,   50,   50,   47,   48,   50,  115,  116,  117,
      119,    0,    0,  124,    0,    0,  129,    0,    0,   50,
       11,   50,   50,   50,   50,   50,   50,   50,   50,   21,

       23,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       43,   46,   50,  120,  121,  122,  125,  126,  127,  130,
      131,  132,   50,   50,   50,   50,   50,   17,   50,   19,
       50,   50,   25,   50,   27,   29,   50,   50,   50,   50,
       50,    9,   12,   13,   50,   50,   18,   20,   50,   50,
       50,   34,   50,   39,   50,   50,   15,   50,   26,   50,
       38,   49,   14,   24,   50,   50,   50,   32,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,   23,   24,   25,   25,   25,   25,   25,
       26,   27,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   26,   44,   45,   46,
       47,   48,   26,   49,   50,   51,   52,   53,   26,   54,
       55,   56,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   61,
       61,   61,    1,   61,    1,    1,   61,   61,   61,   61,
       61,   61,   61,   61,   61,    1,    1,   61,   61,   61,
        1,   61,    1,    1,   61,   61,   61,   61,    1,    1,
        1,    1,    1,    1,   61,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    5,    6,    3,
        1,    1,    1,    1,    7,    1,    8,    1,    1,    1,
        1,    1,    1,    8,    8,    9,    8,   10,   10,   10,
       10,   11,   10,    8,    8,    8,    8,    8,    8,    9,
        8,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    1,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[384] =
    {   0,
        0,    0,  998,  999,  999,  994,  975,   60,  999,  988,
      101,  999,  999,  983,  999,  999,   58,   59,  999,   58,
      999,  999,  979,  157,  999,  999,   60,  157,   63,   64,
      159,  167,  168,  183,  147,   32,  152,  155,   33,  135,
      159,  168,  171,  170,  175,  184,  189,  192,   37,  191,
      999,  934,  999,  999,  999,  988,  999,  999,  999,  999,
      212,  218,  234,  999,  982,  273,  981,  330,  980,  999,
      999,  999,  220,  970,  999,  213,  231,  252,  999,  999,
      999,  975,  999,  963,  999,  970,  999,  999,  999,  999,
      973,  933,  334,  999,  932,  304,   54,  297,  151,  213,

      214,  295,  307,  319,  299,  321,  328,  323,  329,  303,
      931,  930,  332,  341,  333,  339,  327,  340,  196,  305,
      929,  919,  918,  381,  376,  377,  372,  999,  967,  966,
      965,  964,  394,  963,  953,  395,  411,  424,  952,  999,
      999,  999,  958,  999,  444,  406,  366,  367,  404,  369,
      413,  405,  390,  368,  406,  419,  424,  918,  417,  422,
      426,  917,  434,  438,  431,  432,  428,  433,  451,  452,
      454,  443,  226,  446,  916,  457,  445,  450,  459,  455,
      458,  467,  906,  493,  946,  396,  506,  507,  999,  954,
      999,  999,  509,  944,  943,  494,  942,  519,  535,  466,

      477,  909,  476,  499,  497,  496,  519,  514,  518,  526,
      531,  908,  516,  530,  528,  535,  543,  544,  907,  906,
      536,  554,  540,  905,  904,  903,  558,  902,  901,  900,
      556,  899,  549,  547,  553,  566,  930,  584,  600,  587,
      929,  589,  928,  614,  927,  926,  925,  608,  892,  591,
      577,  561,  602,  615,  604,  603,  607,  608,  578,  614,
      620,  626,  616,  630,  891,  621,  890,  629,  889,  888,
      631,  638,  887,  627,  886,  885,  642,  916,  915,  658,
      914,  664,  687,  913,  693,  716,  912,  722,  745,  879,
      878,  667,  635,  660,  685,  666,  670,  686,  665,  877,

      876,  687,  714,  700,  696,  718,  726,  737,  724,  729,
      875,  874,  641,  905,  904,  763,  903,  902,  769,  897,
      896,  785,  742,  859,  719,  741,  762,  858,  854,  851,
      765,  764,  850,  768,  849,  848,  776,  777,  786,  795,
      792,  842,  841,  835,  793,  834,  822,  816,  808,  787,
      796,  805,  790,  802,  797,  799,  794,  804,  785,  806,
      746,  736,  695,  502,  740,  803,  478,  449,  999,  851,
      858,  869,  877,  884,  436,  893,  901,  907,  387,  220,
      191,  162,   84
    } ;

static const flex_int16_t yy_def[384] =
    {   0,
      369,    1,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  370,
      369,  369,  369,  369,  369,  369,  371,  371,  370,  370,
      370,  370,  370,  371,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
      369,  372,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  373,  374,  369,
      369,  369,  375,  369,  369,  369,  370,  370,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      376,   34,  370,  369,   34,   34,   34,   34,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,  372,  372,  369,  369,  369,  369,  369,  369,  377,
      369,  377,  378,  374,  369,  369,  369,  379,  369,  369,
      369,  369,  376,  369,  370,  370,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,  372,  380,  369,  369,  369,  369,  369,  377,
      369,  369,  378,  369,  369,  369,  369,  369,  369,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,  369,  369,  369,  381,
      369,  382,  369,  383,  369,  369,  369,  369,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,  369,  369,  369,  369,  369,  369,  369,
      369,  369,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,    0,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369
    } ;

static const flex_int16_t yy_nxt[1061] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   29,   30,   31,
       32,   33,   33,   34,   28,   35,   36,   37,   38,   28,
       39,   40,   28,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   28,   28,   28,   51,   52,   53,   54,
       55,   58,   71,   73,   59,   75,  106,   75,   91,   98,
       75,   75,   76,   60,   77,   74,   61,  369,  369,   72,
       92,   92,  120,   62,   62,   92,   63,   93,   78,   78,
       78,  288,   78,   62,   62,   62,   62,   62,   62,  151,

       63,   65,   92,   65,   65,   66,   65,   65,   67,   65,
       65,   65,   65,   65,   65,   65,   65,   68,   65,   65,
       65,   65,   65,   65,   68,   68,   68,   68,   69,   69,
       69,   69,   69,   69,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   65,   65,   65,
       65,   65,   80,   81,   75,   91,   75,   82,   83,  285,
       84,  107,   85,  369,   75,   75,   86,   87,   88,   89,
       96,   94,  369,   92,   93,   78,   78,   78,  154,   78,
       75,   91,  108,   97,   99,   92,  104,  100,  282,   92,

       92,  101,  102,   92,  110,  103,  105,   92,  112,  109,
       93,   78,   78,   78,   90,   78,   92,  138,   92,   92,
      111,  114,  116,  113,  121,  118,  124,  238,   61,  139,
      117,   95,   92,  119,  125,  115,  135,   92,   75,   92,
       92,   62,   62,  180,   92,   76,  137,   77,  155,  157,
      126,   62,   62,   62,   62,   62,   62,  127,  127,   75,
      137,   92,   92,  156,  158,  228,  369,  127,  127,  127,
      127,  127,  127,  129,   92,  129,  129,  130,  129,  129,
      131,  129,  129,  129,  129,  129,  129,  129,  129,  130,
      129,  129,  129,  129,  129,  129,  130,  130,  130,  130,

      129,  129,  129,  129,  129,  129,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  129,
      129,  129,  129,  129,  132,  152,  159,  128,  148,  169,
      149,   75,  160,   92,  163,   92,  181,   92,  369,  153,
      145,   92,  150,   92,  161,   92,  164,  134,  134,  134,
      134,  134,  134,  146,  162,  166,  168,   92,  167,   92,
      165,   92,  178,  172,  174,   92,   92,   92,  173,  175,
       92,   92,  177,  176,  179,  184,  188,   92,   92,   92,
      186,  187,  125,  126,  198,  127,  127,  185,  190,  200,

      240,  192,  204,  210,  201,  127,  127,  127,  127,  127,
      127,  194,  241,   75,   92,   92,   92,   92,  136,  136,
      369,  134,  134,  134,  134,  134,  134,  195,  136,  136,
      136,  136,  136,  136,  196,  196,  209,  202,   92,  211,
      197,  203,  208,  136,  196,  196,  196,  196,  196,  196,
      199,   75,   92,   92,   92,  205,  212,  213,  369,  216,
      145,   92,  206,  207,  199,   92,  217,   92,  215,  218,
       92,  220,   92,  146,   92,  219,   92,  221,  223,   92,
       92,   92,   92,  222,  224,  225,   92,  226,  227,  229,
      230,   92,  233,   92,   92,  231,  232,   92,   92,   92,

       92,  234,   92,   92,  235,   92,   92,   92,  236,  237,
      242,  244,  250,  190,   92,   92,  192,  196,  196,  239,
      249,  251,  243,  245,   92,   92,  368,  196,  196,  196,
      196,  196,  196,  239,  252,  246,  134,  134,  134,  134,
      134,  134,  198,  198,   92,   92,  254,   92,  253,  256,
       92,  247,  198,  198,  198,  198,  198,  198,  248,  248,
      255,  257,   92,  261,   92,  263,   92,   92,  248,  248,
      248,  248,  248,  248,   92,  259,   92,  258,   92,   92,
      265,  262,  264,   92,   92,  266,  268,  269,   92,  273,
      270,   92,   92,  271,  274,   92,  275,   92,  276,  277,

      278,   92,   92,  281,   92,  284,   92,  238,  238,   92,
      291,  292,  299,  283,   92,  286,  279,  238,  238,  238,
      238,  238,  238,  280,  280,   92,   92,  283,  290,  286,
      287,  248,  248,  280,  280,  280,  280,  280,  280,   92,
      289,  248,  248,  248,  248,  248,  248,  293,  294,  295,
       92,   92,   92,  296,  289,   92,   92,  301,  298,  297,
      300,  302,   92,   92,   92,  304,  303,  306,   92,   92,
      307,  310,  309,  312,   92,   92,  313,   92,   92,   92,
      314,  280,  280,   92,  341,  325,   92,  282,  282,   92,
       92,  280,  280,  280,  280,  280,  280,  282,  282,  282,

      282,  282,  282,  315,  324,  326,  331,  329,   92,  317,
      316,  316,  328,   92,   92,   92,  285,  285,   92,  330,
      316,  316,  316,  316,  316,  316,  285,  285,  285,  285,
      285,  285,  318,   92,   92,   92,  327,  332,  320,  319,
      319,  334,  335,   92,   92,  288,  288,  333,   92,  319,
      319,  319,  319,  319,  319,  288,  288,  288,  288,  288,
      288,  321,   92,  336,  337,  344,   92,   92,  322,  322,
      338,  339,   92,  340,   92,  342,  366,   92,  322,  322,
      322,  322,  322,  322,   92,   92,  316,  316,   92,   92,
       92,  345,  319,  319,   92,  346,  316,  316,  316,  316,

      316,  316,  319,  319,  319,  319,  319,  319,  322,  322,
       92,  348,   92,   92,  350,  349,   92,  351,  322,  322,
      322,  322,  322,  322,   92,   92,  352,  353,  354,  355,
      356,  360,  359,   92,   92,   92,  361,  364,   92,  365,
       92,   92,   92,   92,   92,   92,  362,   92,  363,  367,
       92,   92,   92,   92,   92,   78,  358,   78,   78,   78,
       78,   78,   92,   92,   92,   92,   92,   92,   92,  122,
       92,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      133,  133,  357,   92,  133,  133,  133,  133,  134,   92,
       92,  134,  134,  134,  134,  143,   92,   92,   92,   92,

      143,  143,  347,  143,  190,  190,   92,  343,  190,  190,
      193,  193,  321,  320,  193,  193,  193,  193,  318,  317,
      315,  314,   92,   92,   92,   92,   92,  323,  287,  284,
      281,  279,  278,   92,   92,  311,  308,   92,   92,  305,
       92,  247,  246,  245,  243,  241,  237,   92,   92,   92,
      272,   92,   92,   92,   92,  267,  260,   92,  197,  195,
      194,  192,  185,  183,   92,   92,  214,  144,  139,  135,
      369,  192,  189,  191,  189,  183,  183,  182,  171,  170,
      147,   92,  144,  142,  141,  140,   74,  128,  128,  128,
       56,  123,   79,   70,   64,   57,   56,  369,    3,  369,

      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369
    } ;

static const flex_int16_t yy_chk[1061] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,   17,   18,    8,   20,   39,   27,   27,   36,
       29,   30,   20,    8,   20,   18,    8,   29,   30,   17,
       36,   39,   49,    8,    8,   49,    8,   27,   27,   27,
       27,  383,   27,    8,    8,    8,    8,    8,    8,   97,

        8,   11,   97,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   24,   24,   28,   28,   31,   24,   24,  382,
       24,   40,   24,   31,   32,   33,   24,   24,   24,   24,
       35,   32,   33,   40,   28,   28,   28,   28,   99,   28,
       34,   34,   41,   35,   37,   35,   38,   37,  381,   99,

       37,   37,   37,   38,   43,   37,   38,   41,   45,   42,
       34,   34,   34,   34,   24,   34,   42,   76,   44,   43,
       44,   46,   47,   45,   50,   48,   61,  380,   61,   76,
       47,   34,   46,   48,   62,   46,   73,   47,   77,   50,
       48,   62,   62,  119,  119,   77,   73,   77,  100,  101,
       63,   62,   62,   62,   62,   62,   62,   63,   63,   78,
       73,  100,  101,  100,  101,  173,   78,   63,   63,   63,
       63,   63,   63,   66,  173,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   68,   98,  102,   68,   96,  110,
       96,   93,  103,  102,  105,   98,  120,  105,   93,   98,
       93,  110,   96,  120,  104,  103,  106,   68,   68,   68,
       68,   68,   68,   93,  104,  107,  109,  104,  108,  106,
      106,  108,  117,  113,  114,  117,  107,  109,  113,  114,
      113,  115,  116,  115,  118,  124,  127,  116,  118,  114,
      125,  126,  125,  126,  379,  127,  127,  124,  133,  147,

      186,  133,  150,  154,  148,  127,  127,  127,  127,  127,
      127,  136,  186,  146,  147,  148,  154,  150,  136,  136,
      146,  133,  133,  133,  133,  133,  133,  137,  136,  136,
      136,  136,  136,  136,  137,  137,  153,  149,  153,  155,
      138,  149,  152,  375,  137,  137,  137,  137,  137,  137,
      138,  145,  149,  152,  155,  151,  156,  157,  145,  160,
      145,  151,  151,  151,  138,  159,  161,  156,  159,  163,
      160,  165,  157,  145,  161,  164,  167,  166,  168,  165,
      166,  168,  163,  167,  169,  170,  164,  171,  172,  174,
      176,  172,  179,  177,  174,  177,  178,  368,  178,  169,

      170,  180,  171,  180,  181,  176,  181,  179,  182,  184,
      187,  188,  201,  193,  200,  182,  193,  196,  196,  184,
      200,  203,  187,  188,  203,  201,  367,  196,  196,  196,
      196,  196,  196,  184,  204,  198,  193,  193,  193,  193,
      193,  193,  198,  198,  206,  205,  206,  204,  205,  208,
      364,  199,  198,  198,  198,  198,  198,  198,  199,  199,
      207,  209,  208,  213,  213,  215,  209,  207,  199,  199,
      199,  199,  199,  199,  210,  211,  215,  210,  214,  211,
      217,  214,  216,  216,  221,  218,  221,  222,  223,  231,
      223,  217,  218,  227,  233,  234,  234,  233,  235,  236,

      238,  235,  222,  240,  231,  242,  227,  238,  238,  252,
      251,  252,  259,  240,  236,  242,  239,  238,  238,  238,
      238,  238,  238,  239,  239,  251,  259,  240,  250,  242,
      244,  248,  248,  239,  239,  239,  239,  239,  239,  250,
      244,  248,  248,  248,  248,  248,  248,  253,  254,  255,
      253,  256,  255,  256,  244,  257,  258,  261,  258,  257,
      260,  262,  260,  254,  263,  264,  263,  266,  261,  266,
      268,  272,  271,  274,  262,  274,  277,  268,  264,  271,
      282,  280,  280,  293,  313,  293,  272,  282,  282,  313,
      277,  280,  280,  280,  280,  280,  280,  282,  282,  282,

      282,  282,  282,  283,  292,  294,  299,  297,  294,  285,
      283,  283,  296,  299,  296,  292,  285,  285,  297,  298,
      283,  283,  283,  283,  283,  283,  285,  285,  285,  285,
      285,  285,  286,  295,  298,  302,  295,  302,  288,  286,
      286,  304,  305,  363,  305,  288,  288,  303,  304,  286,
      286,  286,  286,  286,  286,  288,  288,  288,  288,  288,
      288,  289,  303,  306,  307,  325,  306,  325,  289,  289,
      308,  309,  309,  310,  307,  323,  365,  310,  289,  289,
      289,  289,  289,  289,  362,  308,  316,  316,  365,  326,
      323,  326,  319,  319,  361,  327,  316,  316,  316,  316,

      316,  316,  319,  319,  319,  319,  319,  319,  322,  322,
      327,  331,  332,  331,  334,  332,  334,  337,  322,  322,
      322,  322,  322,  322,  337,  338,  338,  339,  340,  341,
      345,  351,  350,  359,  339,  350,  353,  358,  353,  360,
      341,  345,  357,  340,  351,  355,  355,  356,  356,  366,
      354,  366,  358,  352,  360,  370,  349,  370,  370,  370,
      370,  370,  371,  371,  348,  371,  371,  371,  371,  372,
      347,  372,  372,  372,  372,  372,  372,  372,  372,  372,
      373,  373,  346,  344,  373,  373,  373,  373,  374,  343,
      342,  374,  374,  374,  374,  376,  336,  335,  333,  330,

      376,  376,  329,  376,  377,  377,  328,  324,  377,  377,
      378,  378,  321,  320,  378,  378,  378,  378,  318,  317,
      315,  314,  312,  311,  301,  300,  291,  290,  287,  284,
      281,  279,  278,  276,  275,  273,  270,  269,  267,  265,
      249,  247,  246,  245,  243,  241,  237,  232,  230,  229,
      228,  226,  225,  224,  220,  219,  212,  202,  197,  195,
      194,  190,  185,  183,  175,  162,  158,  143,  139,  135,
      134,  132,  131,  130,  129,  123,  122,  121,  112,  111,
       95,   92,   91,   86,   84,   82,   74,   69,   67,   65,
       56,   52,   23,   14,   10,    7,    6,    3,  369,  369,

      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mini.l"
#line 2 "mini.l"
int lineno = 1;
#include<stdio.h>

#define ARRAY 260
#define CABECERA 261
#define CADA 262
#define CADENA 263
#define CARACTER 264
#define CONJUNTO 265
#define CONSTANTES 266
#define CONTINUAR 267
#define CTC_CADENA 268
#define CTC_CARACTER 269
#define CTC_ENTERA 270
#define CTC_REAL 271
#define DE 272
#define DEFECTO 273
#define DEVOLVER 275
#define EJECUTA 276
#define ENCAMBIO 277
#define ENTERO 278
#define ES 280
#define ESCAPE 281
#define ESTRUCTURA 282
#define ETIQUETA 283
#define EXCEPCION 284
#define FICHERO 289
#define FIN 290
#define FUNCION 291
#define HACER 292
#define HASH 293
#define IDENTIFICADOR 295
#define LANZA 297
#define MIENTRAS 299
#define NADA 302
#define OTRA 305
#define PARA 307
#define PRINCIPIO 309
#define PROGRAMA 310
#define REAL 312
#define REF 313
#define RUTA 315
#define SALTAR 316
#define SI 317
#define SINO 318
#define TAMANO 320
#define TIPOS 321
#define UNION 322
#define VARIABLES 323

#define POTENCIA 311
#define SUMA_ASIG 319
#define RESTA_ASIG 314
#define MULT_ASIG 301
#define DIV_ASIG 274
#define MOD_ASIG 300
#define FD_ASIG 285
#define FI_ASIG 286
#define FLECHA_DCHA 287
#define FLECHA_IZDA 288
#define AND_ASIG 259
#define XOR_ASIG 324
#define OR_ASIG 306
#define POT_ASIG 308
#define GE 294
#define LE 298
#define EQ 279
#define NEQ 303
#define AND 258
#define OR 304
#define INDIRECCION 296

#define DELIMITADOR 324
#define COM_S 325
#define COM_MI 326
#define COM_MF 327
#define FUNC 328
#define OPERADOR 329

#define UNKNOWN 72
#define UNKNOWN_CHAR 73

#line 881 "lex.yy.c"
#line 882 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 93 "mini.l"

#line 1101 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 370 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 999 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 94 "mini.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 95 "mini.l"
return CTC_CARACTER;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 96 "mini.l"
return CTC_CARACTER;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 97 "mini.l"
return CTC_CADENA;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 98 "mini.l"
return CTC_CADENA;
	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 99 "mini.l"
return CTC_CADENA;
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 101 "mini.l"
{lineno++;};
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "mini.l"
return ARRAY;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "mini.l"
return CABECERA;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 105 "mini.l"
return CADA;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "mini.l"
return CADENA;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "mini.l"
return CARACTER;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "mini.l"
return CONJUNTO;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "mini.l"
return CONSTANTES;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "mini.l"
return CONTINUAR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "mini.l"
return DE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "mini.l"
return DEFECTO;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "mini.l"
return DEVOLVER;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "mini.l"
return EJECUTA;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "mini.l"
return ENCAMBIO;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "mini.l"
return ENTERO;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "mini.l"
return ES;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "mini.l"
return ESCAPE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "mini.l"
return ESTRUCTURA;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "mini.l"
return ETIQUETA;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "mini.l"
return EXCEPCION;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "mini.l"
return FICHERO;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "mini.l"
return FIN;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "mini.l"
return FUNCION;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "mini.l"
return HACER;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "mini.l"
return HASH;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 127 "mini.l"
return IDENTIFICADOR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "mini.l"
return LANZA;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "mini.l"
return MIENTRAS;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "mini.l"
return NADA;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "mini.l"
return OTRA;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 132 "mini.l"
return PARA;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "mini.l"
return PRINCIPIO;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "mini.l"
return PROGRAMA;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 135 "mini.l"
return REAL;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "mini.l"
return REF;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "mini.l"
return RUTA;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "mini.l"
return SALTAR;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "mini.l"
return SI;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "mini.l"
return SINO;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 141 "mini.l"
return TAMANO;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "mini.l"
return TIPOS;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 143 "mini.l"
return UNION;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "mini.l"
return VARIABLES;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 146 "mini.l"
return IDENTIFICADOR;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 148 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 149 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 150 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 151 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 152 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 153 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 154 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 155 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 156 "mini.l"
return DELIMITADOR;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 158 "mini.l"
return COM_S;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 159 "mini.l"
return COM_MI;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 160 "mini.l"
return COM_MF;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 162 "mini.l"
return OPERADOR;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 163 "mini.l"
return OPERADOR;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 164 "mini.l"
return OPERADOR;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 165 "mini.l"
return OPERADOR;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 166 "mini.l"
return OPERADOR;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 167 "mini.l"
return OPERADOR;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 168 "mini.l"
return OPERADOR;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 169 "mini.l"
return OPERADOR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 170 "mini.l"
return OPERADOR;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 171 "mini.l"
return OPERADOR;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 172 "mini.l"
return OPERADOR;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 173 "mini.l"
return OPERADOR;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 175 "mini.l"
return POTENCIA;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 176 "mini.l"
return SUMA_ASIG;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 177 "mini.l"
return RESTA_ASIG;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 178 "mini.l"
return MULT_ASIG;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 179 "mini.l"
return DIV_ASIG;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 180 "mini.l"
return MOD_ASIG;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 181 "mini.l"
return FI_ASIG;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 182 "mini.l"
return FD_ASIG;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 183 "mini.l"
return AND_ASIG;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 184 "mini.l"
return XOR_ASIG;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 185 "mini.l"
return OR_ASIG;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 186 "mini.l"
return POT_ASIG;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 187 "mini.l"
return GE;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 188 "mini.l"
return LE;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 189 "mini.l"
return EQ;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 190 "mini.l"
return NEQ;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 191 "mini.l"
return AND;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 192 "mini.l"
return OR;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 193 "mini.l"
return AND;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 194 "mini.l"
return OR;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 195 "mini.l"
return FLECHA_IZDA;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 196 "mini.l"
return FLECHA_DCHA;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 197 "mini.l"
return INDIRECCION;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 199 "mini.l"
return CTC_ENTERA;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 200 "mini.l"
return CTC_ENTERA;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 201 "mini.l"
return CTC_ENTERA;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 202 "mini.l"
return CTC_ENTERA;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 203 "mini.l"
return CTC_ENTERA;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 205 "mini.l"
return CTC_REAL;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 206 "mini.l"
return CTC_REAL;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 207 "mini.l"
return CTC_REAL;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 208 "mini.l"
return CTC_REAL;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 209 "mini.l"
return CTC_REAL;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 211 "mini.l"
return CTC_REAL;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 212 "mini.l"
return CTC_REAL;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 213 "mini.l"
return CTC_REAL;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 214 "mini.l"
return CTC_REAL;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 215 "mini.l"
return CTC_REAL;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 217 "mini.l"
return CTC_REAL;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 218 "mini.l"
return CTC_REAL;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 219 "mini.l"
return CTC_REAL;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 220 "mini.l"
return CTC_REAL;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 221 "mini.l"
return CTC_REAL;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 223 "mini.l"
return CTC_REAL;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 224 "mini.l"
return CTC_REAL;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 225 "mini.l"
return CTC_REAL;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 226 "mini.l"
return CTC_REAL;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 227 "mini.l"
return CTC_REAL;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 229 "mini.l"
return CTC_REAL;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 230 "mini.l"
return CTC_REAL;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 231 "mini.l"
return CTC_REAL;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 232 "mini.l"
return CTC_REAL;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 233 "mini.l"
return CTC_REAL;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 235 "mini.l"
return CTC_REAL;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 236 "mini.l"
return CTC_REAL;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 237 "mini.l"
return CTC_REAL;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 238 "mini.l"
return CTC_REAL;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 239 "mini.l"
return CTC_REAL;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 241 "mini.l"
return RUTA;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 242 "mini.l"
return ARRAY;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 243 "mini.l"
return FUNC;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 244 "mini.l"
return UNKNOWN;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 245 "mini.l"
return UNKNOWN;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 246 "mini.l"
return UNKNOWN_CHAR;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 247 "mini.l"
ECHO;
	YY_BREAK
#line 1857 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 370 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 370 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 369);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 247 "mini.l"


int main(int argc, char *argv[]) {
{
  if (argc < 2) {
    printf("Uso: ./mini NombreArchivo\n");
    }
  else {
    int scan, slcline=0, mlc=0, mlcline=0;
    yyin = fopen(argv[1],"r");
    printf("\n\n");
    scan = yylex();
    while(scan)
    {
      if(lineno == slcline){
        scan = yylex();
        continue;
      }

      if(scan==268 && mlc==0){
        printf("Linea %d, CTC_Cadena: %s\n", lineno, yytext);
      }
      if(scan==269 && mlc==0){
        printf("Linea %d, CTC_Caracter: %s\n", lineno, yytext);
      }
      if(scan==270 && mlc==0){
        printf("Linea %d, CTC_Entera: %s\n", lineno, yytext);
      }
      if(scan==271 && mlc==0){
        printf("Linea %d, CTC_Real: %s\n", lineno, yytext);
      }




      if(((scan>=260 && scan<=267) || (scan>=272 && scan<=273) || (scan>=275 && scan<=279) || (scan>=280 && scan<=284) || (scan>=289 && scan<=293) || scan==297 || scan==299 || scan==302 || scan==305 || scan==307 || scan==309 || scan==310 || scan==312 || scan==313 || scan==316 || scan==317 || scan==318 || scan==320 || scan==321 || scan==322 || scan==323) && mlc==0){
        printf("Linea %d, Palabra Reservada: %s\n", lineno, yytext);
      }




      if(scan==328 && mlc==0){
        printf("Linea %d, Funcion definida por el usuario: %s\n", lineno, yytext);
      }
      if(scan==315 && mlc==0){
        printf("Linea %d, Ruta: %s\n", lineno, yytext);
      }
      if(scan==329 && mlc==0){
        printf("Linea %d, Operador: %s\n", lineno, yytext);
      }
      if(scan==324 && mlc==0){
        printf("Linea %d, Delimitador: %s\n", lineno, yytext);
      }
      if(scan==295 && mlc==0){
        printf("Linea %d, Identificador: %s\n", lineno, yytext);
      }
      if(scan==325){
        printf("Linea %d, Comentario Simple: %s\n", lineno, yytext);
        slcline = lineno;
      }
      if(scan==326 && mlc==0){
        printf("Linea %d, Inicio Comentario Multilinea: %s\n", lineno, yytext);
        mlcline = lineno;
        mlc = 1;
      }
      if(scan==327 && mlc==0){
        printf("Linea %d, ERROR: Fin de Comentario Multilinea sin inicio. %s\n", lineno, yytext);
      }
      if(scan==327 && mlc==1){
        mlc = 0;
        printf("Linea %d, Fin Comentario Multilinea: %s\n", lineno, yytext);
      }
      if(scan==72 && mlc==0){
        printf("ERROR: Linea %d, Cadena incorrecta: %s\n", lineno, yytext);
      }
      if(scan==73 && mlc==0){
        printf("ERROR: Linea %d, Caracter incorrecta: %s\n", lineno, yytext);
      }
      scan = yylex();
    }
    if(mlc==1)
      printf("Linea %d, ERROR: Inicio de Comentario Multilinea sin cierre. %s\n", lineno, yytext);
    printf("\n");
    }
  }

}
int yywrap(){
	return 1;
}
